/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqlPlaygroundRouteImport } from './routes/sql-playground'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MockRouteImport } from './routes/mock'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeCategoryRouteImport } from './routes/practice.$category'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedReadyRouteImport } from './routes/_authenticated/ready'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'

const SqlPlaygroundRoute = SqlPlaygroundRouteImport.update({
  id: '/sql-playground',
  path: '/sql-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MockRoute = MockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeCategoryRoute = PracticeCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PracticeRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReadyRoute = AuthenticatedReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mock': typeof MockRoute
  '/practice': typeof PracticeRouteWithChildren
  '/sql-playground': typeof SqlPlaygroundRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/ready': typeof AuthenticatedReadyRoute
  '/api/chat': typeof ApiChatRoute
  '/practice/$category': typeof PracticeCategoryRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mock': typeof MockRoute
  '/sql-playground': typeof SqlPlaygroundRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/ready': typeof AuthenticatedReadyRoute
  '/api/chat': typeof ApiChatRoute
  '/practice/$category': typeof PracticeCategoryRoute
  '/practice': typeof PracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mock': typeof MockRoute
  '/practice': typeof PracticeRouteWithChildren
  '/sql-playground': typeof SqlPlaygroundRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/ready': typeof AuthenticatedReadyRoute
  '/api/chat': typeof ApiChatRoute
  '/practice/$category': typeof PracticeCategoryRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mock'
    | '/practice'
    | '/sql-playground'
    | '/history'
    | '/ready'
    | '/api/chat'
    | '/practice/$category'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mock'
    | '/sql-playground'
    | '/history'
    | '/ready'
    | '/api/chat'
    | '/practice/$category'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mock'
    | '/practice'
    | '/sql-playground'
    | '/_authenticated/history'
    | '/_authenticated/ready'
    | '/api/chat'
    | '/practice/$category'
    | '/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MockRoute: typeof MockRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  SqlPlaygroundRoute: typeof SqlPlaygroundRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sql-playground': {
      id: '/sql-playground'
      path: '/sql-playground'
      fullPath: '/sql-playground'
      preLoaderRoute: typeof SqlPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock': {
      id: '/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof MockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/$category': {
      id: '/practice/$category'
      path: '/$category'
      fullPath: '/practice/$category'
      preLoaderRoute: typeof PracticeCategoryRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ready': {
      id: '/_authenticated/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof AuthenticatedReadyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedReadyRoute: typeof AuthenticatedReadyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedReadyRoute: AuthenticatedReadyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PracticeRouteChildren {
  PracticeCategoryRoute: typeof PracticeCategoryRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeCategoryRoute: PracticeCategoryRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MockRoute: MockRoute,
  PracticeRoute: PracticeRouteWithChildren,
  SqlPlaygroundRoute: SqlPlaygroundRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
