/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MockRouteImport } from './routes/mock'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as SqlPlaygroundRouteImport } from './routes/sql-playground'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeCategoryRouteImport } from './routes/practice.$category'
import { Route as PrepIndexRouteImport } from './routes/prep.index'
import { Route as PrepJdRouteImport } from './routes/prep.jd'
import { Route as PrepResumeRouteImport } from './routes/prep.resume'
import { Route as PrepTodayRouteImport } from './routes/prep.today'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as PrepPlanIndexRouteImport } from './routes/prep.plan.index'
import { Route as PrepPlanDateRouteImport } from './routes/prep.plan.$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MockRoute = MockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlPlaygroundRoute = SqlPlaygroundRouteImport.update({
  id: '/sql-playground',
  path: '/sql-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeCategoryRoute = PracticeCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PracticeRoute,
} as any)
const PrepIndexRoute = PrepIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrepRoute,
} as any)
const PrepJdRoute = PrepJdRouteImport.update({
  id: '/jd',
  path: '/jd',
  getParentRoute: () => PrepRoute,
} as any)
const PrepResumeRoute = PrepResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => PrepRoute,
} as any)
const PrepTodayRoute = PrepTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => PrepRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepPlanIndexRoute = PrepPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => PrepRoute,
} as any)
const PrepPlanDateRoute = PrepPlanDateRouteImport.update({
  id: '/plan/$date',
  path: '/plan/$date',
  getParentRoute: () => PrepRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mock': typeof MockRoute
  '/practice': typeof PracticeRouteWithChildren
  '/prep': typeof PrepRouteWithChildren
  '/sql-playground': typeof SqlPlaygroundRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/practice/$category': typeof PracticeCategoryRoute
  '/prep/jd': typeof PrepJdRoute
  '/prep/resume': typeof PrepResumeRoute
  '/prep/today': typeof PrepTodayRoute
  '/practice/': typeof PracticeIndexRoute
  '/prep/': typeof PrepIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/prep/plan/$date': typeof PrepPlanDateRoute
  '/prep/plan/': typeof PrepPlanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mock': typeof MockRoute
  '/sql-playground': typeof SqlPlaygroundRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/practice/$category': typeof PracticeCategoryRoute
  '/prep/jd': typeof PrepJdRoute
  '/prep/resume': typeof PrepResumeRoute
  '/prep/today': typeof PrepTodayRoute
  '/practice': typeof PracticeIndexRoute
  '/prep': typeof PrepIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/prep/plan/$date': typeof PrepPlanDateRoute
  '/prep/plan': typeof PrepPlanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mock': typeof MockRoute
  '/practice': typeof PracticeRouteWithChildren
  '/prep': typeof PrepRouteWithChildren
  '/sql-playground': typeof SqlPlaygroundRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/practice/$category': typeof PracticeCategoryRoute
  '/prep/jd': typeof PrepJdRoute
  '/prep/resume': typeof PrepResumeRoute
  '/prep/today': typeof PrepTodayRoute
  '/practice/': typeof PracticeIndexRoute
  '/prep/': typeof PrepIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/prep/plan/$date': typeof PrepPlanDateRoute
  '/prep/plan/': typeof PrepPlanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mock'
    | '/practice'
    | '/prep'
    | '/sql-playground'
    | '/history'
    | '/api/chat'
    | '/practice/$category'
    | '/prep/jd'
    | '/prep/resume'
    | '/prep/today'
    | '/practice/'
    | '/prep/'
    | '/.lovable/oauth/consent'
    | '/prep/plan/$date'
    | '/prep/plan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mock'
    | '/sql-playground'
    | '/history'
    | '/api/chat'
    | '/practice/$category'
    | '/prep/jd'
    | '/prep/resume'
    | '/prep/today'
    | '/practice'
    | '/prep'
    | '/.lovable/oauth/consent'
    | '/prep/plan/$date'
    | '/prep/plan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mock'
    | '/practice'
    | '/prep'
    | '/sql-playground'
    | '/_authenticated/history'
    | '/api/chat'
    | '/practice/$category'
    | '/prep/jd'
    | '/prep/resume'
    | '/prep/today'
    | '/practice/'
    | '/prep/'
    | '/.lovable/oauth/consent'
    | '/prep/plan/$date'
    | '/prep/plan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MockRoute: typeof MockRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  PrepRoute: typeof PrepRouteWithChildren
  SqlPlaygroundRoute: typeof SqlPlaygroundRoute
  ApiChatRoute: typeof ApiChatRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock': {
      id: '/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof MockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-playground': {
      id: '/sql-playground'
      path: '/sql-playground'
      fullPath: '/sql-playground'
      preLoaderRoute: typeof SqlPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/$category': {
      id: '/practice/$category'
      path: '/$category'
      fullPath: '/practice/$category'
      preLoaderRoute: typeof PracticeCategoryRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/prep/': {
      id: '/prep/'
      path: '/'
      fullPath: '/prep/'
      preLoaderRoute: typeof PrepIndexRouteImport
      parentRoute: typeof PrepRoute
    }
    '/prep/jd': {
      id: '/prep/jd'
      path: '/jd'
      fullPath: '/prep/jd'
      preLoaderRoute: typeof PrepJdRouteImport
      parentRoute: typeof PrepRoute
    }
    '/prep/resume': {
      id: '/prep/resume'
      path: '/resume'
      fullPath: '/prep/resume'
      preLoaderRoute: typeof PrepResumeRouteImport
      parentRoute: typeof PrepRoute
    }
    '/prep/today': {
      id: '/prep/today'
      path: '/today'
      fullPath: '/prep/today'
      preLoaderRoute: typeof PrepTodayRouteImport
      parentRoute: typeof PrepRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep/plan/': {
      id: '/prep/plan/'
      path: '/plan'
      fullPath: '/prep/plan/'
      preLoaderRoute: typeof PrepPlanIndexRouteImport
      parentRoute: typeof PrepRoute
    }
    '/prep/plan/$date': {
      id: '/prep/plan/$date'
      path: '/plan/$date'
      fullPath: '/prep/plan/$date'
      preLoaderRoute: typeof PrepPlanDateRouteImport
      parentRoute: typeof PrepRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PracticeRouteChildren {
  PracticeCategoryRoute: typeof PracticeCategoryRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeCategoryRoute: PracticeCategoryRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

interface PrepRouteChildren {
  PrepJdRoute: typeof PrepJdRoute
  PrepResumeRoute: typeof PrepResumeRoute
  PrepTodayRoute: typeof PrepTodayRoute
  PrepIndexRoute: typeof PrepIndexRoute
  PrepPlanDateRoute: typeof PrepPlanDateRoute
  PrepPlanIndexRoute: typeof PrepPlanIndexRoute
}

const PrepRouteChildren: PrepRouteChildren = {
  PrepJdRoute: PrepJdRoute,
  PrepResumeRoute: PrepResumeRoute,
  PrepTodayRoute: PrepTodayRoute,
  PrepIndexRoute: PrepIndexRoute,
  PrepPlanDateRoute: PrepPlanDateRoute,
  PrepPlanIndexRoute: PrepPlanIndexRoute,
}

const PrepRouteWithChildren = PrepRoute._addFileChildren(PrepRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MockRoute: MockRoute,
  PracticeRoute: PracticeRouteWithChildren,
  PrepRoute: PrepRouteWithChildren,
  SqlPlaygroundRoute: SqlPlaygroundRoute,
  ApiChatRoute: ApiChatRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
